devastator := ../..

include $(devastator)/makefile

app := gvt-test

gvt-test.hxxs = $(devastator/src)/gvt.hxx \
                $(devastator/world.hxxs)

gvt-test.cxxs = gvt-test.cxx \
                $(devastator/src)/gvt.cxx \
                $(devastator/world.cxxs)
