devastator := ../..

app = gvt-test

gvt-test.deps = $(devastator/src)/gvt.hxx \
                $(devastator/world.deps)

gvt-test.srcs = gvt-test.cxx \
                $(devastator/src)/gvt.cxx \
                $(devastator/world.srcs)

include $(devastator)/makefile
